export default {
  id: '05-bare-metal',
  title: 'Setup on Bare Metal & Linux',
  icon: '\u{1F5A5}\u{FE0F}',
  colorHex: '#7B1FA2',
  description: 'Step-by-step installation guides for Ubuntu, macOS, Windows WSL, and DGX Spark.',
  difficulty: 'intermediate',
  estimatedHours: 6,
  prerequisites: ['03-nemoclaw-architecture'],
  chapters: [
    {
      id: 'c1-prerequisites',
      title: 'Prerequisites & System Requirements',
      description: 'Hardware, software, and platform requirements.',
      estimatedMinutes: 30,
      sections: [
        { id: 's1-hardware-requirements', title: 'Hardware Requirements', difficulty: 'beginner', readingMinutes: 8, description: '4+ vCPU, 8-16 GB RAM, 20-40 GB disk requirements.' },
        { id: 's2-software-requirements', title: 'Software Requirements', difficulty: 'beginner', readingMinutes: 10, description: 'Node.js 20+, npm 10+, Docker, and Git.' },
        { id: 's3-supported-distros', title: 'Supported Distributions', difficulty: 'beginner', readingMinutes: 8, description: 'Platform support tiers and kernel version matrix.' },
      ],
    },
    {
      id: 'c2-ubuntu-22',
      title: 'Ubuntu 22.04 Setup',
      description: 'Complete installation walkthrough on Ubuntu 22.04 LTS.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-installing-deps', title: 'Installing Dependencies', difficulty: 'beginner', readingMinutes: 10, description: 'apt, NodeSource, and Docker CE installation.' },
        { id: 's2-docker-config', title: 'Docker Configuration', difficulty: 'beginner', readingMinutes: 10, description: 'Docker group, daemon.json, and storage driver setup.' },
        { id: 's3-nemoclaw-onboard', title: 'Running nemoclaw onboard', difficulty: 'beginner', readingMinutes: 12, description: 'Install script, blueprint download, and sandbox creation.' },
        { id: 's4-verifying-install', title: 'Verifying Installation', difficulty: 'beginner', readingMinutes: 10, description: 'Status checks, connection test, and verification script.' },
        { id: 's5-troubleshooting', title: 'Troubleshooting', difficulty: 'intermediate', readingMinutes: 12, description: 'Docker issues, port conflicts, RAM, and disk space.' },
      ],
    },
    {
      id: 'c3-ubuntu-24-dgx',
      title: 'Ubuntu 24.04 & DGX Spark',
      description: 'cgroup v2 fixes and DGX-specific optimizations.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-cgroup-v2', title: 'cgroup v2 Considerations', difficulty: 'intermediate', readingMinutes: 10, description: 'cgroup v1 vs v2 and container runtime compatibility.' },
        { id: 's2-setup-spark', title: 'Running setup-spark', difficulty: 'intermediate', readingMinutes: 10, description: 'The nemoclaw setup-spark command explained.' },
        { id: 's3-dgx-optimizations', title: 'DGX Optimizations', difficulty: 'advanced', readingMinutes: 12, description: 'Unified memory, GPU allocation, and MPS configuration.' },
        { id: 's4-gpu-passthrough', title: 'GPU Passthrough', difficulty: 'advanced', readingMinutes: 12, description: 'nvidia-container-toolkit and device mapping.' },
      ],
    },
    {
      id: 'c4-macos',
      title: 'macOS Setup',
      description: 'Installation via Colima or Docker Desktop on macOS.',
      estimatedMinutes: 40,
      sections: [
        { id: 's1-colima-vs-docker', title: 'Colima vs Docker Desktop', difficulty: 'beginner', readingMinutes: 10, description: 'Comparing the two container runtimes for macOS.' },
        { id: 's2-installation-walkthrough', title: 'Installation Walkthrough', difficulty: 'beginner', readingMinutes: 12, description: 'Homebrew, Colima, Node.js, and NemoClaw setup.' },
        { id: 's3-macos-limitations', title: 'macOS Limitations', difficulty: 'intermediate', readingMinutes: 10, description: 'No host Landlock, network namespace differences, no GPU.' },
        { id: 's4-apple-silicon', title: 'Apple Silicon Considerations', difficulty: 'intermediate', readingMinutes: 8, description: 'ARM64 support, Rosetta, and VZ vs QEMU.' },
      ],
    },
    {
      id: 'c5-windows-wsl',
      title: 'Windows (WSL2) Setup',
      description: 'Running NemoClaw inside Windows Subsystem for Linux.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-wsl2-config', title: 'WSL2 Configuration', difficulty: 'beginner', readingMinutes: 10, description: 'Enable WSL2, install Ubuntu, and configure .wslconfig.' },
        { id: 's2-docker-desktop-wsl', title: 'Docker Desktop with WSL', difficulty: 'beginner', readingMinutes: 10, description: 'Docker Desktop WSL2 backend setup.' },
        { id: 's3-installation-walkthrough', title: 'Installation Walkthrough', difficulty: 'beginner', readingMinutes: 12, description: 'Full NemoClaw install inside WSL2.' },
        { id: 's4-windows-troubleshooting', title: 'Windows Troubleshooting', difficulty: 'intermediate', readingMinutes: 12, description: 'Networking, DNS, VPN interference, and memory issues.' },
      ],
    },
    {
      id: 'c6-post-install',
      title: 'Post-Installation',
      description: 'First connection, health checks, logs, and updates.',
      estimatedMinutes: 40,
      sections: [
        { id: 's1-first-connection', title: 'First Connection', difficulty: 'beginner', readingMinutes: 10, description: 'nemoclaw connect and initial sandbox exploration.' },
        { id: 's2-health-checks', title: 'Health Checks', difficulty: 'beginner', readingMinutes: 10, description: 'Status commands and component health states.' },
        { id: 's3-logs-diagnostics', title: 'Logs & Diagnostics', difficulty: 'intermediate', readingMinutes: 10, description: 'Log locations, audit logs, debug mode, and diagnostic bundles.' },
        { id: 's4-updating', title: 'Updating & Upgrading', difficulty: 'beginner', readingMinutes: 8, description: 'CLI updates, blueprint upgrades, and rollback.' },
      ],
    },
  ],
}
