export default {
  id: '06-cloud-setup',
  title: 'Setup on Public Clouds & VPS',
  icon: '\u{2601}\u{FE0F}',
  colorHex: '#00897B',
  description: 'Deploy NemoClaw on AWS, GCP, Azure, popular VPS providers, NVIDIA Brev, and self-hosted infrastructure.',
  difficulty: 'intermediate',
  estimatedHours: 8,
  prerequisites: ['05-bare-metal'],
  chapters: [
    {
      id: 'c1-fundamentals',
      title: 'Cloud Deployment Fundamentals',
      description: 'Instance selection, security groups, and remote access.',
      estimatedMinutes: 30,
      sections: [
        { id: 's1-choosing-instances', title: 'Choosing Instance Types', difficulty: 'beginner', readingMinutes: 10, description: 'CPU, RAM, and disk sizing for NemoClaw workloads.' },
        { id: 's2-security-groups', title: 'Security Groups & Networking', difficulty: 'intermediate', readingMinutes: 10, description: 'Firewall rules and port configuration for NemoClaw.' },
        { id: 's3-remote-access', title: 'Remote Access Patterns', difficulty: 'intermediate', readingMinutes: 10, description: 'SSH tunneling, VS Code Remote, and Tailscale.' },
      ],
    },
    {
      id: 'c2-aws',
      title: 'AWS Deployment',
      description: 'EC2 setup, IAM, GPU instances, and cost optimization.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-ec2-setup', title: 'EC2 Instance Setup', difficulty: 'intermediate', readingMinutes: 10, description: 'Launching t3.large+ instances for NemoClaw.' },
        { id: 's2-security-iam', title: 'Security Groups & IAM', difficulty: 'intermediate', readingMinutes: 12, description: 'AWS security configuration and role-based access.' },
        { id: 's3-installation-aws', title: 'NemoClaw on AWS', difficulty: 'intermediate', readingMinutes: 12, description: 'Installation on Amazon Linux and Ubuntu AMI.' },
        { id: 's4-gpu-instances', title: 'GPU Instances', difficulty: 'advanced', readingMinutes: 10, description: 'p3 and g4dn instances for local inference.' },
        { id: 's5-cost-optimization', title: 'Cost Optimization', difficulty: 'intermediate', readingMinutes: 10, description: 'Spot instances, reserved pricing, and right-sizing.' },
      ],
    },
    {
      id: 'c3-gcp',
      title: 'Google Cloud Deployment',
      description: 'Compute Engine, firewall rules, GPU VMs, and GKE.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-compute-engine', title: 'Compute Engine Setup', difficulty: 'intermediate', readingMinutes: 10, description: 'Creating and configuring GCP VMs for NemoClaw.' },
        { id: 's2-firewall-rules', title: 'Firewall & Service Accounts', difficulty: 'intermediate', readingMinutes: 12, description: 'GCP firewall rules and IAM service accounts.' },
        { id: 's3-installation-gcp', title: 'NemoClaw on GCP', difficulty: 'intermediate', readingMinutes: 12, description: 'Installation walkthrough on GCP.' },
        { id: 's4-gpu-vms', title: 'GPU VMs (A100/T4)', difficulty: 'advanced', readingMinutes: 10, description: 'Attaching GPUs for local inference workloads.' },
        { id: 's5-gke-integration', title: 'GKE Integration', difficulty: 'advanced', readingMinutes: 10, description: 'Experimental Kubernetes deployment on GKE.' },
      ],
    },
    {
      id: 'c4-azure',
      title: 'Microsoft Azure Deployment',
      description: 'Azure VMs, NSG, managed identity, and GPU instances.',
      estimatedMinutes: 55,
      sections: [
        { id: 's1-azure-vm', title: 'Azure VM Setup', difficulty: 'intermediate', readingMinutes: 10, description: 'Creating Azure VMs for NemoClaw.' },
        { id: 's2-nsg-identity', title: 'NSG & Managed Identity', difficulty: 'intermediate', readingMinutes: 12, description: 'Network security groups and Azure identity.' },
        { id: 's3-installation-azure', title: 'NemoClaw on Azure', difficulty: 'intermediate', readingMinutes: 12, description: 'Installation walkthrough on Azure.' },
        { id: 's4-gpu-vms-azure', title: 'GPU VMs (NC-series)', difficulty: 'advanced', readingMinutes: 10, description: 'NC-series VMs for local GPU inference.' },
        { id: 's5-azure-config', title: 'Azure-Specific Configuration', difficulty: 'intermediate', readingMinutes: 10, description: 'Performance tuning and Azure-specific settings.' },
      ],
    },
    {
      id: 'c5-vps-providers',
      title: 'Popular VPS Providers',
      description: 'DigitalOcean, Hetzner, Vultr, Linode, and Oracle Cloud.',
      estimatedMinutes: 50,
      sections: [
        { id: 's1-digitalocean', title: 'DigitalOcean Droplets', difficulty: 'beginner', readingMinutes: 10, description: 'NemoClaw on DigitalOcean droplets.' },
        { id: 's2-hetzner', title: 'Hetzner Cloud', difficulty: 'beginner', readingMinutes: 10, description: 'Cost-effective European cloud deployment.' },
        { id: 's3-vultr', title: 'Vultr', difficulty: 'beginner', readingMinutes: 10, description: 'NemoClaw on Vultr cloud compute.' },
        { id: 's4-linode', title: 'Linode / Akamai', difficulty: 'beginner', readingMinutes: 10, description: 'Deployment on Linode/Akamai cloud.' },
        { id: 's5-oracle-free', title: 'Oracle Cloud Free Tier', difficulty: 'beginner', readingMinutes: 10, description: 'Running NemoClaw on Oracle always-free instances.' },
      ],
    },
    {
      id: 'c6-nvidia-brev',
      title: 'NVIDIA Brev (Remote GPU)',
      description: 'Deploy to remote GPU instances via NVIDIA Brev.',
      estimatedMinutes: 40,
      sections: [
        { id: 's1-what-is-brev', title: 'What is Brev?', difficulty: 'beginner', readingMinutes: 8, description: 'NVIDIA\'s remote GPU deployment platform.' },
        { id: 's2-deploy-walkthrough', title: 'Deploy Walkthrough', difficulty: 'intermediate', readingMinutes: 12, description: 'nemoclaw deploy step-by-step.' },
        { id: 's3-a100-config', title: 'Tesla A100 Configuration', difficulty: 'advanced', readingMinutes: 10, description: 'Configuring A100 GPUs for inference.' },
        { id: 's4-persistent-ephemeral', title: 'Persistent vs Ephemeral', difficulty: 'intermediate', readingMinutes: 8, description: 'Choosing between persistent and ephemeral deployments.' },
      ],
    },
    {
      id: 'c7-self-hosted',
      title: 'Self-Hosted & Hybrid',
      description: 'Proxmox, Tailscale, and multi-node deployments.',
      estimatedMinutes: 30,
      sections: [
        { id: 's1-proxmox-homelab', title: 'Proxmox / Homelab', difficulty: 'intermediate', readingMinutes: 10, description: 'Running NemoClaw on Proxmox and homelab setups.' },
        { id: 's2-tailscale-wireguard', title: 'Tailscale & WireGuard', difficulty: 'intermediate', readingMinutes: 10, description: 'Secure remote access with mesh VPNs.' },
        { id: 's3-multi-node', title: 'Multi-Node Deployments', difficulty: 'advanced', readingMinutes: 10, description: 'Scaling NemoClaw across multiple nodes.' },
      ],
    },
  ],
}
