export default {
  id: '07-applications',
  title: 'Practical Applications & Use Cases',
  icon: '\u{1F680}',
  colorHex: '#F57C00',
  description: 'Build real-world solutions: always-on assistants, Telegram bots, CI/CD agents, multi-agent systems, and enterprise deployments.',
  difficulty: 'advanced',
  estimatedHours: 8,
  prerequisites: ['04-policies', '05-bare-metal'],
  chapters: [
    {
      id: 'c1-always-on-assistant',
      title: 'Always-On AI Coding Assistant',
      description: 'Persistent dev agent with workspace configuration and memory.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-persistent-agent', title: 'Setting Up a Persistent Agent', difficulty: 'intermediate', readingMinutes: 12, description: 'systemd service setup for always-on operation.' },
        { id: 's2-workspace-config', title: 'Workspace Configuration', difficulty: 'intermediate', readingMinutes: 10, description: 'SOUL.md, IDENTITY.md, USER.md, and MEMORY.md.' },
        { id: 's3-project-api-restrict', title: 'Restricting to Project APIs', difficulty: 'intermediate', readingMinutes: 10, description: 'Scoping network policies to project-specific endpoints.' },
        { id: 's4-memory-persistence', title: 'Memory Persistence', difficulty: 'intermediate', readingMinutes: 10, description: 'Strategies for persisting agent memory across sessions.' },
      ],
    },
    {
      id: 'c2-sandboxed-testing',
      title: 'Sandboxed Agent Testing Lab',
      description: 'Testing agent behavior safely before production.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-testing-before-prod', title: 'Testing Before Production', difficulty: 'intermediate', readingMinutes: 10, description: 'Five-phase testing methodology for agent behavior.' },
        { id: 's2-graduated-permissions', title: 'Graduated Permission Escalation', difficulty: 'intermediate', readingMinutes: 12, description: 'L0-L4 permission ladder for progressive trust.' },
        { id: 's3-monitoring-logging', title: 'Monitoring & Logging', difficulty: 'intermediate', readingMinutes: 12, description: 'Configuring monitoring and log collection for agents.' },
        { id: 's4-ab-testing', title: 'A/B Testing Configurations', difficulty: 'advanced', readingMinutes: 10, description: 'Testing different agent configurations side by side.' },
      ],
    },
    {
      id: 'c3-telegram-bot',
      title: 'Telegram Bot Integration',
      description: 'Running an AI agent as a Telegram bot.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-telegram-policy', title: 'Telegram Policy Setup', difficulty: 'intermediate', readingMinutes: 10, description: 'Configuring the Telegram policy preset.' },
        { id: 's2-bot-config', title: 'Bot Configuration', difficulty: 'intermediate', readingMinutes: 12, description: 'BotFather setup and webhook configuration.' },
        { id: 's3-interactive-agent', title: 'Interactive Agent via Messaging', difficulty: 'intermediate', readingMinutes: 12, description: 'Commands, file sharing, and interactive features.' },
        { id: 's4-rate-limiting', title: 'Rate Limiting & Abuse Prevention', difficulty: 'intermediate', readingMinutes: 10, description: 'Rate limits, cost caps, and abuse prevention.' },
      ],
    },
    {
      id: 'c4-multi-agent',
      title: 'Multi-Agent Coordination',
      description: 'Running multiple agents with defined roles and boundaries.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-agents-md', title: 'AGENTS.md Workspace Files', difficulty: 'intermediate', readingMinutes: 10, description: 'Defining agent roles in AGENTS.md format.' },
        { id: 's2-agent-roles', title: 'Defining Agent Roles', difficulty: 'intermediate', readingMinutes: 12, description: 'Specialized roles and responsibility boundaries.' },
        { id: 's3-inter-agent-comms', title: 'Inter-Agent Communication', difficulty: 'advanced', readingMinutes: 12, description: 'Communication channels and message routing patterns.' },
        { id: 's4-shared-isolated', title: 'Shared vs Isolated Sandboxes', difficulty: 'advanced', readingMinutes: 10, description: 'Trade-offs between shared and isolated sandbox environments.' },
      ],
    },
    {
      id: 'c5-cicd-agent',
      title: 'CI/CD Pipeline Agent',
      description: 'Integrating AI agents into CI/CD workflows.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-agent-code-review', title: 'Agent-Assisted Code Review', difficulty: 'intermediate', readingMinutes: 12, description: 'Using agents for automated code review in CI.' },
        { id: 's2-automated-testing', title: 'Automated Testing', difficulty: 'intermediate', readingMinutes: 10, description: 'Agent-driven test generation with sandbox isolation.' },
        { id: 's3-ci-policy-config', title: 'CI Policy Configuration', difficulty: 'intermediate', readingMinutes: 10, description: 'Minimal policies for CI/CD environments.' },
        { id: 's4-github-actions', title: 'GitHub Actions Integration', difficulty: 'intermediate', readingMinutes: 12, description: 'Complete GitHub Actions workflow for agent-assisted CI.' },
      ],
    },
    {
      id: 'c6-research',
      title: 'Research & Experimentation',
      description: 'Running experiments, benchmarks, and custom blueprints.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-isolated-experiments', title: 'Isolated Experiments', difficulty: 'intermediate', readingMinutes: 12, description: 'Reproducible ML experiments in sandboxed environments.' },
        { id: 's2-comparing-providers', title: 'Comparing Inference Providers', difficulty: 'intermediate', readingMinutes: 10, description: 'Benchmarking methodology for provider comparison.' },
        { id: 's3-benchmarking', title: 'Benchmarking Agent Performance', difficulty: 'advanced', readingMinutes: 12, description: 'Performance metrics and benchmarking frameworks.' },
        { id: 's4-custom-blueprints', title: 'Custom Blueprint Development', difficulty: 'advanced', readingMinutes: 10, description: 'Building custom blueprint templates for research.' },
      ],
    },
    {
      id: 'c7-enterprise',
      title: 'Enterprise & Compliance',
      description: 'SOC2, audit trails, RBAC, and data residency.',
      estimatedMinutes: 45,
      sections: [
        { id: 's1-soc2-deployment', title: 'SOC2-Friendly Deployment', difficulty: 'advanced', readingMinutes: 12, description: 'Mapping NemoClaw controls to SOC2 requirements.' },
        { id: 's2-audit-trails', title: 'Audit Trails', difficulty: 'intermediate', readingMinutes: 10, description: 'Audit trail configuration and log retention.' },
        { id: 's3-role-based-access', title: 'Role-Based Operator Access', difficulty: 'advanced', readingMinutes: 12, description: 'RBAC with SSO integration for operators.' },
        { id: 's4-data-residency', title: 'Data Residency & Routing', difficulty: 'advanced', readingMinutes: 10, description: 'Regional endpoint routing and data sovereignty.' },
      ],
    },
  ],
}
